# Generated by Django 4.2.16 on 2024-12-21 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField(default=0)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Image', models.ImageField(upload_to='book_media')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('Reason', models.TextField(max_length=200)),
                ('sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.sex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
