# Generated by Django 4.2.16 on 2024-12-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_patient_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_deleted',
        ),
    ]
